### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by JamoBox** [JamoBox/django-notify#1]
Add Travis CI integration - for now (as we don't have tests) just get a skeleton together for it that passes.

**Comment by JamoBox** [comment]
https://docs.travis-ci.com/user/languages/python/
https://github.com/almcc/cinder-data/blob/master/.travis.yml

**Comment by VesnaBrucoms** [comment]
If I'm understanding the docs correctly, does the nightly version test against the version of Python currently in beta?

**Comment by JamoBox** [comment]
@VesnaBrucoms sort of, it tests against Python's nightly build, which *latest* build of python available in active development. This gives us the quickest possible idea of whether or not our project will work with whatever the next python release is.

**Comment by JamoBox** [comment]
Now implemented in master

**Comment by VesnaBrucoms** [comment]
Understood.
